version: '3'
services:
  mongodb:
    image: arm64v8/mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - plan2go

  mongo-express:
    image: mongo-express
    ports:
      - "8084:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # - ME_CONFIG_MONGODB_URI=mongodb://admin:password@mongodb:27017/admin?authMechanism=SCRAM-SHA-256
    depends_on:
      - mongodb
    networks:
      - plan2go

  UserServer:
    image: plan2go/user_server:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/admin?authMechanism=SCRAM-SHA-256
      - TravelNoteServerLocation=http://TravelNoteServer:8082
      - PostServerLocation=http://PostServer:8083
    depends_on:
      - mongodb
    networks:
      - plan2go

  TravelNoteServer:
    image: plan2go/travel_note_server:latest
    ports:
      - "8082:8082"
    depends_on:
        - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/admin?authMechanism=SCRAM-SHA-256
      - UserServerLocation=http://UserServer:8081
      - PostServerLocation=http://PostServer:8083
    networks:
      - plan2go
  

  PostServer:
    image: plan2go/post_server:latest
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/admin?authMechanism=SCRAM-SHA-256
      - UserServerLocation=http://UserServer:8081
      - TravelNoteServerLocation=http://TravelNoteServer:8082
    networks:
      - plan2go

  Client:
    image: plan2go/client:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - UserServer
      - TravelNoteServer
      - PostServer
    networks:
      - plan2go
#
#  localstack:
#    image: localstack/localstack
#    ports:
#      - 4566:4566
#    environment:
#      - SERVICES:s3
#      - AWS_ACCESS_KEY_ID=foo
#      - AWS_SECRET_ACCESS_KEY=bar
#      - AWS_DEFAULT_REGION=eu-central-2
#    networks:
#      - plan2go
#

networks:
  plan2go:
    driver: bridge


