version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - spaghetticode

  mongo-express:
    image: mongo-express
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - spaghetticode

  UserServer:
    image: plan2go/user_server:latest
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  TravelNoteServer:
    image: plan2go/travel_note_server:latest
    ports:
      - "8082:8082"
    depends_on:
        - mongodb
    networks:
      - spaghetticode

  Client:
    image: plan2go/client:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - UserServer
      - TravelNoteServer
    networks:
      - spaghetticode

networks:
  spaghetticode:
    driver: bridge


